baseURL = "https://www.habitante.org/"
defaultContentLanguage = "es"
title = "Habitante.org"
theme = "minimo"

[params.info]
description = "Mirada ecosocial a los temas que mueven"
title404 = "Página no encontrada"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
gopher = ""

[params.settings]
accentColor = "#3d7e9a"

[params.copyright]
prefix = "<span style=\"display:none\">"
holder = "Habitante.org"
startYear = "2019"
suffix = "</span><a rel=\"license\" href=\"http://creativecommons.org/licenses/by-nc-nd/4.0/\"><img alt=\"Licencia Creative Commons\" style=\"border-width:0\" src=\"https://i.creativecommons.org/l/by-nc-nd/4.0/80x15.png\" /></a><br />Esta obra está bajo una <a rel=\"license\" href=\"http://creativecommons.org/licenses/by-nc-nd/4.0/\">Licencia Creative Commons Atribución-NoComercial-SinDerivadas 4.0 Internacional</a>."

[params.widgets]
header = ["breadcrumbs"]
homepage = ["recent_posts"]
footer = ["social_menu"]

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[markup.goldmark.renderer]
unsafe= true

[languages.es]
lang = "es"
languageName = "Spanish"
weight = 1

[params.social]
twitter = "HabitanteOrg"
email = "habitante@protonmail.com"
github = "habitanteorg"
gitlab = "habitanteorg"

[taxonomies]
author = "authors"
categories = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"
ciencia = "/:year/:section/:slug"
cronica = "/:year/:section/:slug"
comenta = "/:year/:section/:slug"

